  # **PROGRAM ASSIGNMENT #2 (NUMPY)**
  ##### **SEPTEMBER 8, 2026**

In [2]:
import numpy as np

### **A. REPRODUCIBLE NORMALIZATION PROBLEM**

In [97]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
Z = (X - np.mean(X)) / (np.std(X))
X_normalized = Z

np.save('X normalized.npy', X_normalized)

In [96]:
print ("X array: \n", X)
print ("\n X_normalized: \n", X_normalized)
print ("\n X_normalized mean: ", (round (np.mean (X_normalized))))
print ("\n X_normalized standard deviation: ", (round(np.std (X_normalized))))

X array: 
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

 X_normalized: 
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

 X_normalized mean:  0

 X_normalized standard deviation:  1


### **B. CUBES DIVISIBLE BY 4 PROBLEM**

In [100]:
c = np.arange (1, 101, 1)
C = np.power (c,3)
C = C.reshape (10,10)
div_by_4 = C[C % 4 == 0]

np.save('div_by_4.npy', div_by_4)

In [99]:
print ("Shape of C array: ",  C.shape)
print ("\n div_by_4 array: \n",  div_by_4)
print ("\n Number of Values in div_by_4: ", len(div_by_4))

Shape of C array:  (10, 10)

 div_by_4 array: 
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

 Number of Values in div_by_4:  50


### **C. ABOVE-MEAN SQUARES PROBLEM**

In [101]:
S = np.arange (1, 37, 1)
S = np.power (S,2)
S = S.reshape (6,6)
S_mean = np.mean(S)
above_mean = S[S > S_mean ]

np.save('above_mean', above_mean)

In [87]:
print ("S array \n", S, "\n")
print ("Mean of S array: \n ", S_mean, "\n")
print ("Above mean array: \n", above_mean, "\n")
print ("Number of above mean values: ", len(above_mean))

S array 
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]] 

Mean of S array: 
  450.1666666666667 

Above mean array: 
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296] 

Number of above mean values:  15


### **Submitted by: Labayan, Princess Noreen**
#### 2ECEA